# Generated by Django 4.2.7 on 2023-12-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_quesmodel_id_alter_userresult_id'),
    ]

    operations = [
    ]
