# Generated by Django 4.2.7 on 2023-12-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20231202_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
