# Generated by Django 4.2.7 on 2023-12-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_test_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
