# Generated by Django 4.2.7 on 2023-12-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_test_time_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('original_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.test')),
            ],
        ),
    ]
