# Generated by Django 5.0 on 2023-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_testcopy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCopy',
        ),
    ]
