# Generated by Django 4.2.7 on 2023-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_test_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
