# Generated by Django 4.2.7 on 2023-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_remove_test_is_started_remove_test_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
