# Generated by Django 4.2.7 on 2023-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_test_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('WA', 'Written Answer')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
