# Generated by Django 4.2.7 on 2023-12-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0020_customuser_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
    ]
