# Generated by Django 4.2.7 on 2023-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0021_remove_customuser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('subjects', models.ManyToManyField(related_name='custom_groups', to='Quiz.subject')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_groups',
            field=models.ManyToManyField(blank=True, help_text='The custom groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user', to='Quiz.customgroup', verbose_name='custom groups'),
        ),
    ]
