# Generated by Django 4.2.7 on 2023-12-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0023_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='Quiz.customgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
