# Generated by Django 4.2.7 on 2023-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0026_alter_test_end_time_alter_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
