# Generated by Django 4.2.7 on 2023-12-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0027_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='user',
            new_name='custom_user',
        ),
    ]
