# Generated by Django 4.2.7 on 2023-12-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0028_rename_user_userresult_custom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='custom_user',
            new_name='user',
        ),
    ]
