# Generated by Django 4.2.7 on 2023-12-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0029_rename_custom_user_userresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='user_answer',
        ),
    ]
