# Generated by Django 4.2.7 on 2023-12-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0030_remove_quesmodel_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_started',
        ),
        migrations.AddField(
            model_name='test',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
