# Generated by Django 4.2.7 on 2023-12-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0031_remove_test_is_started_test_time_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time_started',
        ),
    ]
