# Generated by Django 4.2.7 on 2023-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0032_remove_test_time_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
