# Generated by Django 4.2.7 on 2023-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0033_userresult_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
