# Generated by Django 4.2.7 on 2023-12-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0034_alter_userresult_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
