# Generated by Django 4.2.7 on 2023-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0036_remove_test_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
